
name: update ini

on:
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually trigger to generate the .ini file.'
  push:
    paths:
      - self_direct.list
      - self_proxy.list
      - update_ini.py
      
permissions:
  contents: write
    
jobs:
  update_ini:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
      - name: Get current date
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: execute py script
        run: |
          python update_ini.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [[ `git status --porcelain` ]]; then
            echo "OK: Changes detected."
            git commit -m "Automatically generated - $NOW"
            git push
          else
            echo "WARNING: No changes were detected."
          fi
